const contractAddress = "0xE26d7A2625eaB1f1bEF0b937B292bB660F42BCd6"; // Replace with your own contract address
const chain = 'goerli'; // goerli, polygon, or ethereum

const welcome_h1 = "Welcome to the Beans X HyperHuman: Genesis NFT Project";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'The Beans X HyperHuman NFT: Genesis Project is a decentralized project that aims to empower people to reach their full potential through the use of non-fungible tokens (NFTs). Our NFTs are unique digital assets that represent various aspects of human growth and development, such as creativity, self-improvement, and personal growth.';
const h1_presale_coming_soon = "NFT Drop Coming Soon";
const h1_presale_mint = "Pre-Sale Minting Open";
const h1_public_mint = "Public Minting Open";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale..";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale..";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you.";
const p_public_mint = "No whitelist needed. Public minting is now open.";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The HyperHuman Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. Please try again.";
